apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
      - image: atortola/rancher-demo:latest
        name: rancher-demo
        ports:
        - containerPort: 8080
        env:
            - name: COW_COLOR
              value: red
            - name: pets
              value: moby
        resources: {}
