kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
  selector:
    application: hello-world